### PR TITLE
Badge&button component

### PR DESCRIPTION
**Pull request by ShekharDhangar**
I have added Badge and Button Components. Please review those. Also refer screenshot or preview link for visuals.
image
image

### CODE REVIEW

**Comment by Hamza-777** [comment]
Everything looks nice to me Shekhar good work..

**Review by shahbazibnafzal — APPROVED** [review]
Looks good Shekhar

**Comment by anik31** [comment]
LGTM

**Comment by ShekharDhangar** [comment]
Thankyou for reviews

**Pull request merged**
