### PR TITLE
Update: Updated components style and Added ALL Components CSS File in…

### PR DESCRIPTION
**Pull request by ShekharDhangar**
Updated Style of Components and added All Components Styles in One file. Please refer deploy link for visuals.

### CODE REVIEW

**Comment by vrx29** [comment]
If this is just a components repo. Either put all the components on one single page or put that navigation on all the pages. Everytime user has to go back and change the component

**Comment by ShekharDhangar** [comment]
> If this is just a components repo. Either put all the components on one single page or put that navigation on all the pages. Everytime user has to go back and change the component

Can you please explain a bit? The component folder has each component in different folder and the navigation is on the site. Also the style of every component is in single other file.

**Review by VLeads — APPROVED** [review]
Amazing UI and code looks good. Keep up doing the good work !!

**Review by animeshgarai09 — APPROVED** [review]

**Review by Dev-AkshatGupta — COMMENTED** [review]
LGTM :) Great work shekhar

**Pull request merged**
